services:
    # general
    everlution.navigation.yaml_parser:
        class: Symfony\Component\Yaml\Parser

    everlution.navigation.yaml_navigation_provider:
        class: Everlution\NavigationBundle\Provider\YamlNavigationProvider
        arguments:
            - '@everlution.navigation.item_factory'
        tags:
            - { name: everlution.navigation_provider }

    everlution.navigation.item_factory:
        class: Everlution\NavigationBundle\Factory\YamlNavigationItemFactory
        arguments:
            - '@everlution.navigation.yaml_parser'
            - '%everlution.navigation.yaml_dir%'
        calls:
            - ['addHydrator', ['@everlution.navigation.hydrator.navigation_item']]
            - ['addHydrator', ['@everlution.navigation.hydrator.prefixed_navigation_item']]
            - ['addHydrator', ['@everlution.navigation.hydrator.root_navigation_item']]
            - ['addHydrator', ['@everlution.navigation.hydrator.route_navigation_item']]
            - ['addHydrator', ['@everlution.navigation.hydrator.regex_navigation_item']]

    # hydrators
    everlution.navigation.hydrator.root_navigation_item:
        class: Everlution\Navigation\Factory\Build\Hydrator\RootNavigationItem

    everlution.navigation.hydrator.navigation_item:
        class: Everlution\Navigation\Factory\Build\Hydrator\NavigationItem

    everlution.navigation.hydrator.prefixed_navigation_item:
        class: Everlution\Navigation\Factory\Build\Hydrator\PrefixedNavigationItem

    everlution.navigation.hydrator.route_navigation_item:
        class: Everlution\Navigation\Factory\Build\Hydrator\RouteNavigationItem

    everlution.navigation.hydrator.regex_navigation_item:
        class: Everlution\Navigation\Factory\Build\Hydrator\RegexNavigationItem

    # registry
    everlution.navigation.register:
        class: Everlution\Navigation\Registry\NavigationRegistry

    # voters
    everlution.navigation.uri_voter:
        class: Everlution\NavigationBundle\Voter\UriVoter
        arguments:
            - '@request_stack'

    everlution.navigation.route_voter:
        class: Everlution\NavigationBundle\Voter\RouteVoter
        arguments:
            - '@request_stack'

    everlution.navigation.prefix_voter:
        class: Everlution\NavigationBundle\Voter\PrefixVoter
        arguments:
            - '@request_stack'

    everlution.navigation.regex_voter:
        class: Everlution\NavigationBundle\Voter\RegexVoter
        arguments:
            - '@request_stack'

    everlution.navigation.manual_voter:
        class: Everlution\Navigation\Voter\ManualVoter
        calls:
            - ['addVoter', ['@everlution.navigation.uri_voter']]
            - ['addVoter', ['@everlution.navigation.route_voter']]
            - ['addVoter', ['@everlution.navigation.prefix_voter']]
            - ['addVoter', ['@everlution.navigation.regex_voter']]

    # matchers
    everlution.navigation.uri_matcher:
        class: Everlution\Navigation\Matcher\NavigationItemMatcher
        calls:
            - ['addVoter', ['@everlution.navigation.uri_voter']]
            - ['addVoter', ['@everlution.navigation.route_voter']]
            - ['addVoter', ['@everlution.navigation.prefix_voter']]
            - ['addVoter', ['@everlution.navigation.regex_voter']]
            - ['addVoter', ['@everlution.navigation.manual_voter']]
