services:
    # general
    everlution.navigation.yaml_parser:
        class: Symfony\Component\Yaml\Parser

    everlution.navigation.yaml_navigation_provider:
        class: Everlution\NavigationBundle\Provider\YamlNavigationProvider
        arguments:
            - '@everlution.navigation.item_factory'
        tags:
            - { name: everlution.navigation_provider }

    everlution.navigation.item_factory:
        class: Everlution\NavigationBundle\Navigation\NavigationItemFactory
        arguments:
            - '@everlution.navigation.yaml_parser'
            - '%everlution.navigation.yaml_dir%'

    everlution.navigation.register:
        class: Everlution\Navigation\Registry\NavigationRegistry

    # voters
    everlution.navigation.uri_voter:
        class: Everlution\NavigationBundle\Voter\UriVoter
        arguments:
            - '@request_stack'

    everlution.navigation.route_voter:
        class: Everlution\NavigationBundle\Voter\RouteVoter
        arguments:
            - '@request_stack'

    # matchers
    everlution.navigation.uri_matcher:
        class: Everlution\Navigation\Matcher\NavigationItemMatcher
        calls:
            - ['addVoter', ['@everlution.navigation.uri_voter']]

